### ISSUE TITLE
How to serialize/deserialize current context, or at least the span+baggage?

### ISSUE THREAD

**Issue by TheBestPessimist** [micrometer-metrics/context-propagation#287]
I am scheduling and then running some tasks with https://github.com/kagkarlsson/db-scheduler.

Because that library uses the database and a threadpool to run my tasks, when a task starts running, all the context i had when i scheduled the task is lost (i'm interested in `traceId`, `spanId` and all the `baggage` fields).

I am looking for a way to persist that particular data (serialize with jackson, for example), then inside the task, as the first step: deserialize the data, and init the context with that data, as if i was continuing the existing trace.

What i tried is to serialize
```
ContextSnapshotFactory.builder().build().captureAll()
```

and 

```
tracer.currentTraceContext().context()
```

but none of these 2 are serializable. 

I think an option is to persist `MDC.getCopyOfContextMap()` and then set those back, but I'm not sure that is the correct way to do it.

Alternatively, how would one go about persisting the current context?

**Comment by jonatan-ivanov** [comment]
You might want to know about the Observation API in [](https://github.com/micrometer-metrics/micrometer) and that [Micrometer Tracing](https://github.com/micrometer-metrics/tracing) contains the tracing bits but I think you should open an issue for the db-scheduler project and ask them to instrument it with the Observation API.

I'm not sure I 100% get what you mean by serializing and persisting the tracing data, where do you want to save it? Btw we support these scenarios, but I think you might want to look at the Observation API for this instead of the context-propagation library. For example in case of HTTP, Kafka, AMQP, etc. we "serialize" the tracing information (there are multiple supported formats: W3C, B3) and send it on the wire in the message headers. You might want to check the classes in the [`io.micrometer.observation.transport`](https://github.com/micrometer-metrics/micrometer/tree/main/micrometer-observation/src/main/java/io/micrometer/observation/transport) package, they can set/extract tracing data. Where you write it to and read it from is up to you.

Also, here is the docs about how to instrument things: https://docs.micrometer.io/micrometer/reference/observation/instrumenting.html

You might also be aware the JDBC support for Micrometer: https://github.com/jdbc-observations/datasource-micrometer

**Comment by jonatan-ivanov** [comment]
I see, this seems very similar to the Kafka/RabbitMQ scenarios we have (since they are async) but it is also somewhat similar to the HTTP client scenario (except that one is sync).

What I think you should do is to extend the DTO that contains the data to execute the task and add some kind of a `Map` (key-value holder) to it. Once you have this, you can create a sender and receive context that knows how to write and read this key-value holder.
This is exactly how HTTP server+client, Kafka, RabbitMQ instrumentations work in Spring and in Micrometer. Here's an [example](https://github.com/micrometer-metrics/micrometer/blob/c7d16cd332dfb9046d205195293f1ccea0589b8b/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/okhttp3/OkHttpContext.java#L56-L60) how we instrument okhttp and set the tracing information to the http headers key-value holder). The receiver side is similar but instead of a setter, you call a getter.

See: https://docs.micrometer.io/micrometer/reference/observation/instrumenting.html

If you have further questions and need more help, you can find us on Slack: https://slack.micrometer.io/
