### ISSUE TITLE
ContextExecutorService.wrap should check whether executor service is already wrapped

### ISSUE THREAD

**Issue by ummels** [micrometer-metrics/context-propagation#319]
At the moment, each call to `ContextExecutorService.wrap` creates a new wrapper around the given executor service.

Wouldn't it make sense to check whether the given executor service is an instance of `ContextExecutorService` and put the wrapper around the executor service contained in that wrapper then?

**Comment by rstoyanchev** [comment]
I tend to agree with @chemicL. We assume you wouldn't pass an already decorated ExecutorService, but should be more explicit about it. To me it sounds like something that shouldn't be silently unwrapped and wrapped again, but if you can better describe the scenario when this occurs, then it might make more sense.

**Comment by ummels** [comment]
We have an immutable API for tasks which looks like this:

```
interface Task {

    Task runOn(ExecutorService executor);

    ...
}
```

if the user calls `runOn`, the given `ExecutorService` might already be wrapped or not. In any case, the generated task should run on a wrapped executor, so I was tempted to just call `ContextExecutorService::wrap` in my implementation.

Of course, if this method is just called once, it is not a big problem, but the method might potentially be called more than once.

**Comment by chemicL** [comment]
@rstoyanchev I'm not sure whether we should assume one would not pass an already decorated `ExecutorService`. And we don't. We make no assumptions from what I can see. I can imagine a scenario where one layer deals with one kind of `Supplier<ContextSnapshot>` and in another layer a different concern is addressed. We should not make any such inference with `instanceof` or other means that would sabotage such code patterns. Not specifying anything can be used to an advantage IMO. WDYT?

For the provided example with an implementation of the given API, an `instanceof` check could be performed, but it's the same concern as above. Perhaps instead of enforcing wrapping, a log warning could be triggered for a failure of the type check, e.g. `"Provided instance is not a ContextExecutorService - this can lead to ThreadLocal state being lost"`. Other than that, perhaps the instances of ExecutorService should be managed in the application, e.g. as Spring Beans which can be automatically wrapped at app startup.

**Comment by chemicL** [comment]
As per the above justification and proposed workaround, we decided to decline the proposal.
